sudo: false

language: python
python:
 - 2.7

addons:
  apt:
    sources:
      - libsdl1.2debian
      - libfdt1
      - libpixman-1-0

before_install:
 - chmod +x ./scripts/ciinstall
 - pip install virtualenv

install: ./scripts/ciinstall

before_script:
 - chmod +x ./scripts/cibuild
script: ./scripts/cibuild

env:
  global:
    - PEBBLE_TOOL=4.3
